//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recauda_InternalService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Recauda_InternalService.InternalServiceSoap")]
    internal interface InternalServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCobro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_InternalService.CobroDTO> GetCobroAsync(System.Guid token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCobroByBUIId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_InternalService.CobroDTO> GetCobroByBUIIdAsync(System.Guid buiId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotificarPostbackBUI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> NotificarPostbackBUIAsync(System.Guid idCobro, System.Guid idPostback, string nroBui, System.DateTime fechaPago, string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PersistirPagoRapipago", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> PersistirPagoRapipagoAsync(string codBarras, System.DateTime fechaPago, System.DateTime fechaProcesamiento, decimal importe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAndSyncTransaccionDecidir_old", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_InternalService.TransaccionDecidir> GetAndSyncTransaccionDecidir_oldAsync(string nroOperacion, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAndSyncTransaccionDecidir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_InternalService.TransaccionDecidir> GetAndSyncTransaccionDecidirAsync(string nroOperacion, string userName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CobroDTO
    {
        
        private System.Guid tokenField;
        
        private string nombreTramiteField;
        
        private int nroCbteField;
        
        private System.DateTime fechaPagoField;
        
        private string tipoPersonaField;
        
        private string tipoDocField;
        
        private string apellidoyNombreField;
        
        private string emailField;
        
        private string documentoField;
        
        private ItemDTO[] conceptosField;
        
        private byte[] pdfField;
        
        private string observacionField;
        
        private System.Nullable<System.Guid> guidBUIField;
        
        private string nroBUIField;
        
        private string emisorField;
        
        private double totalField;
        
        private string canalPagoField;
        
        private string medioPagoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreTramite
        {
            get
            {
                return this.nombreTramiteField;
            }
            set
            {
                this.nombreTramiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int NroCbte
        {
            get
            {
                return this.nroCbteField;
            }
            set
            {
                this.nroCbteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime FechaPago
        {
            get
            {
                return this.fechaPagoField;
            }
            set
            {
                this.fechaPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TipoPersona
        {
            get
            {
                return this.tipoPersonaField;
            }
            set
            {
                this.tipoPersonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TipoDoc
        {
            get
            {
                return this.tipoDocField;
            }
            set
            {
                this.tipoDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ApellidoyNombre
        {
            get
            {
                return this.apellidoyNombreField;
            }
            set
            {
                this.apellidoyNombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Documento
        {
            get
            {
                return this.documentoField;
            }
            set
            {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public ItemDTO[] Conceptos
        {
            get
            {
                return this.conceptosField;
            }
            set
            {
                this.conceptosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=10)]
        public byte[] Pdf
        {
            get
            {
                return this.pdfField;
            }
            set
            {
                this.pdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Observacion
        {
            get
            {
                return this.observacionField;
            }
            set
            {
                this.observacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<System.Guid> GuidBUI
        {
            get
            {
                return this.guidBUIField;
            }
            set
            {
                this.guidBUIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string NroBUI
        {
            get
            {
                return this.nroBUIField;
            }
            set
            {
                this.nroBUIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Emisor
        {
            get
            {
                return this.emisorField;
            }
            set
            {
                this.emisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public double Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string CanalPago
        {
            get
            {
                return this.canalPagoField;
            }
            set
            {
                this.canalPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string MedioPago
        {
            get
            {
                return this.medioPagoField;
            }
            set
            {
                this.medioPagoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ItemDTO
    {
        
        private System.Guid idField;
        
        private string codigoField;
        
        private string descripcionField;
        
        private decimal importeField;
        
        private int cantidadField;
        
        private decimal precioUnitarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Importe
        {
            get
            {
                return this.importeField;
            }
            set
            {
                this.importeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Cantidad
        {
            get
            {
                return this.cantidadField;
            }
            set
            {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal PrecioUnitario
        {
            get
            {
                return this.precioUnitarioField;
            }
            set
            {
                this.precioUnitarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SubTransaccionDecidir
    {
        
        private decimal montoField;
        
        private int cuotasField;
        
        private string nroTicketField;
        
        private string estadoField;
        
        private string motivoField;
        
        private string codAutField;
        
        private string nroComercioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Monto
        {
            get
            {
                return this.montoField;
            }
            set
            {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Cuotas
        {
            get
            {
                return this.cuotasField;
            }
            set
            {
                this.cuotasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NroTicket
        {
            get
            {
                return this.nroTicketField;
            }
            set
            {
                this.nroTicketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Motivo
        {
            get
            {
                return this.motivoField;
            }
            set
            {
                this.motivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CodAut
        {
            get
            {
                return this.codAutField;
            }
            set
            {
                this.codAutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NroComercio
        {
            get
            {
                return this.nroComercioField;
            }
            set
            {
                this.nroComercioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransaccionDecidir
    {
        
        private string nroOperacionField;
        
        private System.DateTime fechaField;
        
        private decimal montoField;
        
        private int cuotasField;
        
        private string nroTicketField;
        
        private string estadoField;
        
        private string motivoField;
        
        private string titularField;
        
        private string sexoField;
        
        private string tipoDocField;
        
        private string nroDocField;
        
        private string codAutField;
        
        private string nroTarjField;
        
        private string emailField;
        
        private string nroComercioField;
        
        private string medioDePagoField;
        
        private string idMedioDePagoField;
        
        private string calleField;
        
        private string nroPuertaField;
        
        private System.DateTime fechaVtoCta1Field;
        
        private SubTransaccionDecidir[] subTransaccionesField;
        
        private string ticketField;
        
        private string paymentIdField;
        
        private string monedaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NroOperacion
        {
            get
            {
                return this.nroOperacionField;
            }
            set
            {
                this.nroOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Monto
        {
            get
            {
                return this.montoField;
            }
            set
            {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Cuotas
        {
            get
            {
                return this.cuotasField;
            }
            set
            {
                this.cuotasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NroTicket
        {
            get
            {
                return this.nroTicketField;
            }
            set
            {
                this.nroTicketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Motivo
        {
            get
            {
                return this.motivoField;
            }
            set
            {
                this.motivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Titular
        {
            get
            {
                return this.titularField;
            }
            set
            {
                this.titularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Sexo
        {
            get
            {
                return this.sexoField;
            }
            set
            {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string TipoDoc
        {
            get
            {
                return this.tipoDocField;
            }
            set
            {
                this.tipoDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string NroDoc
        {
            get
            {
                return this.nroDocField;
            }
            set
            {
                this.nroDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CodAut
        {
            get
            {
                return this.codAutField;
            }
            set
            {
                this.codAutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string NroTarj
        {
            get
            {
                return this.nroTarjField;
            }
            set
            {
                this.nroTarjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string NroComercio
        {
            get
            {
                return this.nroComercioField;
            }
            set
            {
                this.nroComercioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string MedioDePago
        {
            get
            {
                return this.medioDePagoField;
            }
            set
            {
                this.medioDePagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string IdMedioDePago
        {
            get
            {
                return this.idMedioDePagoField;
            }
            set
            {
                this.idMedioDePagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Calle
        {
            get
            {
                return this.calleField;
            }
            set
            {
                this.calleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string NroPuerta
        {
            get
            {
                return this.nroPuertaField;
            }
            set
            {
                this.nroPuertaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public System.DateTime FechaVtoCta1
        {
            get
            {
                return this.fechaVtoCta1Field;
            }
            set
            {
                this.fechaVtoCta1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=20)]
        public SubTransaccionDecidir[] SubTransacciones
        {
            get
            {
                return this.subTransaccionesField;
            }
            set
            {
                this.subTransaccionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Ticket
        {
            get
            {
                return this.ticketField;
            }
            set
            {
                this.ticketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string PaymentId
        {
            get
            {
                return this.paymentIdField;
            }
            set
            {
                this.paymentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Moneda
        {
            get
            {
                return this.monedaField;
            }
            set
            {
                this.monedaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    internal interface InternalServiceSoapChannel : Recauda_InternalService.InternalServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    internal partial class InternalServiceSoapClient : System.ServiceModel.ClientBase<Recauda_InternalService.InternalServiceSoap>, Recauda_InternalService.InternalServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InternalServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(InternalServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), InternalServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InternalServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InternalServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InternalServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InternalServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InternalServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Recauda_InternalService.CobroDTO> GetCobroAsync(System.Guid token)
        {
            return base.Channel.GetCobroAsync(token);
        }
        
        public System.Threading.Tasks.Task<Recauda_InternalService.CobroDTO> GetCobroByBUIIdAsync(System.Guid buiId)
        {
            return base.Channel.GetCobroByBUIIdAsync(buiId);
        }
        
        public System.Threading.Tasks.Task<bool> NotificarPostbackBUIAsync(System.Guid idCobro, System.Guid idPostback, string nroBui, System.DateTime fechaPago, string user, string pass)
        {
            return base.Channel.NotificarPostbackBUIAsync(idCobro, idPostback, nroBui, fechaPago, user, pass);
        }
        
        public System.Threading.Tasks.Task<bool> PersistirPagoRapipagoAsync(string codBarras, System.DateTime fechaPago, System.DateTime fechaProcesamiento, decimal importe)
        {
            return base.Channel.PersistirPagoRapipagoAsync(codBarras, fechaPago, fechaProcesamiento, importe);
        }
        
        public System.Threading.Tasks.Task<Recauda_InternalService.TransaccionDecidir> GetAndSyncTransaccionDecidir_oldAsync(string nroOperacion, string userName)
        {
            return base.Channel.GetAndSyncTransaccionDecidir_oldAsync(nroOperacion, userName);
        }
        
        public System.Threading.Tasks.Task<Recauda_InternalService.TransaccionDecidir> GetAndSyncTransaccionDecidirAsync(string nroOperacion, string userName)
        {
            return base.Channel.GetAndSyncTransaccionDecidirAsync(nroOperacion, userName);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.InternalServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.InternalServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.InternalServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:59337/InternalService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.InternalServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:59337/InternalService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            InternalServiceSoap,
            
            InternalServiceSoap12,
        }
    }
}
