//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recauda_PagosService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Recauda_PagosService.PagosServiceSoap")]
    internal interface PagosServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConceptos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_PagosService.Concepto[]> GetConceptosAsync(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConceptosVigentes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_PagosService.Concepto[]> GetConceptosVigentesAsync(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetImporte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_PagosService.Concepto[]> GetImporteAsync(Recauda_PagosService.Concepto[] conceptos, string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTokenExpediente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_PagosService.GetTokenExpedienteResponse> GetTokenExpedienteAsync(Recauda_PagosService.GetTokenExpedienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTokenBUIPE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_PagosService.RespuestaGetTokenBUI> GetTokenBUIPEAsync(System.Guid buId, string user, string pass, System.Guid idMiBA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTokenBUI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_PagosService.RespuestaGetTokenBUI> GetTokenBUIAsync(System.Guid buId, string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTokenBUIAuth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_PagosService.GetTokenBUIAuthResponse> GetTokenBUIAuthAsync(Recauda_PagosService.GetTokenBUIAuthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTokenDueDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_PagosService.GetTokenDueDateResponse> GetTokenDueDateAsync(Recauda_PagosService.GetTokenDueDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_PagosService.GetTokenResponse> GetTokenAsync(Recauda_PagosService.GetTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTokenPagoVoluntario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_PagosService.GetTokenPagoVoluntarioResponse> GetTokenPagoVoluntarioAsync(Recauda_PagosService.GetTokenPagoVoluntarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstadoPago", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_PagosService.EstadoPago> GetEstadoPagoAsync(System.Guid token, string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstadoPagoV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_PagosService.EstadoPagoV2> GetEstadoPagoV2Async(System.Guid token, string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstadoPagos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_PagosService.EstadoPagoV2[]> GetEstadoPagosAsync(System.DateTime desde, System.DateTime hasta, string tipoDoc, string nroDoc, string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstadoPagoSuaci", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_PagosService.EstadoPago> GetEstadoPagoSuaciAsync(string nroSuaci, string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTimbradoDigital", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetTimbradoDigitalAsync(System.Guid token, string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMedioPagoPorIdCobro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetMedioPagoPorIdCobroAsync(System.Guid idCobro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCodigoAutorizacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetCodigoAutorizacionAsync(System.Guid idCobro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcesarBajaFacturaPMC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ProcesarBajaFacturaPMCAsync(string token, string nroBoleta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarCbteDePagoPorEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Recauda_PagosService.PDFResponse> EnviarCbteDePagoPorEmailAsync(System.Guid token, System.Guid userId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Concepto
    {
        
        private string codigoField;
        
        private string descripcionField;
        
        private int cantidadField;
        
        private bool precioFijoField;
        
        private decimal importeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Cantidad
        {
            get
            {
                return this.cantidadField;
            }
            set
            {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool PrecioFijo
        {
            get
            {
                return this.precioFijoField;
            }
            set
            {
                this.precioFijoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Importe
        {
            get
            {
                return this.importeField;
            }
            set
            {
                this.importeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseResult
    {
        
        private ResponseResultMessages codigoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseResultMessages codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ResponseResultMessages
    {
        
        /// <remarks/>
        ErrorGenérico,
        
        /// <remarks/>
        RespuestaExitosa,
        
        /// <remarks/>
        NoEstaPagadaLaBoleta,
        
        /// <remarks/>
        ErrorEnLaGeneraciónDelPDF,
        
        /// <remarks/>
        ErrorGuardarPDF,
        
        /// <remarks/>
        NoExisteBoleta,
        
        /// <remarks/>
        DependenciaIncorrecta,
        
        /// <remarks/>
        PagoInexistente,
        
        /// <remarks/>
        TimbreInexistente,
        
        /// <remarks/>
        ComprobanteInexistente,
        
        /// <remarks/>
        Regularizar,
        
        /// <remarks/>
        ValoresInesperadosBody,
        
        /// <remarks/>
        PDFInexistente,
        
        /// <remarks/>
        MaximoVersioPermitido,
        
        /// <remarks/>
        ComprobanteNoDisponible,
        
        /// <remarks/>
        TokenInexistente,
        
        /// <remarks/>
        EmailInvalido,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PDFResponse
    {
        
        private string tokenField;
        
        private byte[] pdfField;
        
        private string fileNameField;
        
        private ResponseResult respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] pdf
        {
            get
            {
                return this.pdfField;
            }
            set
            {
                this.pdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ResponseResult respuesta
        {
            get
            {
                return this.respuestaField;
            }
            set
            {
                this.respuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EstadoPagoV2
    {
        
        private System.Guid tokenField;
        
        private Concepto[] conceptosField;
        
        private decimal importeTotalField;
        
        private string medioPagoField;
        
        private string nroCbteField;
        
        private System.Nullable<System.DateTime> fechaPagoField;
        
        private System.DateTime fechaEmisionField;
        
        private System.DateTime fechaVencimientoField;
        
        private string boletaNroField;
        
        private System.Nullable<System.DateTime> fechaVencimientoBuiField;
        
        private string nroExpedienteField;
        
        private string idTramiteDependenciaField;
        
        private string nombreTramiteField;
        
        private string observacionField;
        
        private string barcodePostbackField;
        
        private Contribuyente contribuyenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Concepto[] Conceptos
        {
            get
            {
                return this.conceptosField;
            }
            set
            {
                this.conceptosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal ImporteTotal
        {
            get
            {
                return this.importeTotalField;
            }
            set
            {
                this.importeTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MedioPago
        {
            get
            {
                return this.medioPagoField;
            }
            set
            {
                this.medioPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NroCbte
        {
            get
            {
                return this.nroCbteField;
            }
            set
            {
                this.nroCbteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> FechaPago
        {
            get
            {
                return this.fechaPagoField;
            }
            set
            {
                this.fechaPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime FechaEmision
        {
            get
            {
                return this.fechaEmisionField;
            }
            set
            {
                this.fechaEmisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime FechaVencimiento
        {
            get
            {
                return this.fechaVencimientoField;
            }
            set
            {
                this.fechaVencimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string BoletaNro
        {
            get
            {
                return this.boletaNroField;
            }
            set
            {
                this.boletaNroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> FechaVencimientoBui
        {
            get
            {
                return this.fechaVencimientoBuiField;
            }
            set
            {
                this.fechaVencimientoBuiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string NroExpediente
        {
            get
            {
                return this.nroExpedienteField;
            }
            set
            {
                this.nroExpedienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string IdTramiteDependencia
        {
            get
            {
                return this.idTramiteDependenciaField;
            }
            set
            {
                this.idTramiteDependenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string NombreTramite
        {
            get
            {
                return this.nombreTramiteField;
            }
            set
            {
                this.nombreTramiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Observacion
        {
            get
            {
                return this.observacionField;
            }
            set
            {
                this.observacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string BarcodePostback
        {
            get
            {
                return this.barcodePostbackField;
            }
            set
            {
                this.barcodePostbackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public Contribuyente Contribuyente
        {
            get
            {
                return this.contribuyenteField;
            }
            set
            {
                this.contribuyenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Contribuyente
    {
        
        private string tipoPersonaField;
        
        private string tipoDocField;
        
        private string generoField;
        
        private string apellidoyNombreField;
        
        private string documentoField;
        
        private string direccionField;
        
        private string pisoField;
        
        private string deptoField;
        
        private string localidadField;
        
        private string codPostField;
        
        private string emailField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private System.Nullable<System.DateTime> fechaNacimientoField;
        
        private string provinciaField;
        
        private string telefonoField;
        
        private string celularField;
        
        private string paisDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TipoPersona
        {
            get
            {
                return this.tipoPersonaField;
            }
            set
            {
                this.tipoPersonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TipoDoc
        {
            get
            {
                return this.tipoDocField;
            }
            set
            {
                this.tipoDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Genero
        {
            get
            {
                return this.generoField;
            }
            set
            {
                this.generoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ApellidoyNombre
        {
            get
            {
                return this.apellidoyNombreField;
            }
            set
            {
                this.apellidoyNombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Documento
        {
            get
            {
                return this.documentoField;
            }
            set
            {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Piso
        {
            get
            {
                return this.pisoField;
            }
            set
            {
                this.pisoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Depto
        {
            get
            {
                return this.deptoField;
            }
            set
            {
                this.deptoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Localidad
        {
            get
            {
                return this.localidadField;
            }
            set
            {
                this.localidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CodPost
        {
            get
            {
                return this.codPostField;
            }
            set
            {
                this.codPostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Apellido
        {
            get
            {
                return this.apellidoField;
            }
            set
            {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> FechaNacimiento
        {
            get
            {
                return this.fechaNacimientoField;
            }
            set
            {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Provincia
        {
            get
            {
                return this.provinciaField;
            }
            set
            {
                this.provinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Celular
        {
            get
            {
                return this.celularField;
            }
            set
            {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string PaisDocumento
        {
            get
            {
                return this.paisDocumentoField;
            }
            set
            {
                this.paisDocumentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EstadoPago
    {
        
        private System.Guid tokenField;
        
        private Concepto[] conceptosField;
        
        private decimal importeTotalField;
        
        private string medioPagoField;
        
        private string nroCbteField;
        
        private System.Nullable<System.DateTime> fechaPagoField;
        
        private string observacionField;
        
        private string iDTramiteDependenciaField;
        
        private string barcodePostbackField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Concepto[] Conceptos
        {
            get
            {
                return this.conceptosField;
            }
            set
            {
                this.conceptosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal ImporteTotal
        {
            get
            {
                return this.importeTotalField;
            }
            set
            {
                this.importeTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MedioPago
        {
            get
            {
                return this.medioPagoField;
            }
            set
            {
                this.medioPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NroCbte
        {
            get
            {
                return this.nroCbteField;
            }
            set
            {
                this.nroCbteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> FechaPago
        {
            get
            {
                return this.fechaPagoField;
            }
            set
            {
                this.fechaPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Observacion
        {
            get
            {
                return this.observacionField;
            }
            set
            {
                this.observacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string IDTramiteDependencia
        {
            get
            {
                return this.iDTramiteDependenciaField;
            }
            set
            {
                this.iDTramiteDependenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string BarcodePostback
        {
            get
            {
                return this.barcodePostbackField;
            }
            set
            {
                this.barcodePostbackField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RespuestaGetTokenBUI
    {
        
        private int statusCodeField;
        
        private string statusDescriptionField;
        
        private System.Nullable<System.Guid> tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string statusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.Guid> token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenExpediente", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetTokenExpedienteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Recauda_PagosService.Contribuyente contribuyente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Recauda_PagosService.Concepto[] conceptos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string nroExpediente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string observacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string pass;
        
        public GetTokenExpedienteRequest()
        {
        }
        
        public GetTokenExpedienteRequest(Recauda_PagosService.Contribuyente contribuyente, Recauda_PagosService.Concepto[] conceptos, string nroExpediente, string observacion, string user, string pass)
        {
            this.contribuyente = contribuyente;
            this.conceptos = conceptos;
            this.nroExpediente = nroExpediente;
            this.observacion = observacion;
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenExpedienteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetTokenExpedienteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> GetTokenExpedienteResult;
        
        public GetTokenExpedienteResponse()
        {
        }
        
        public GetTokenExpedienteResponse(System.Nullable<System.Guid> GetTokenExpedienteResult)
        {
            this.GetTokenExpedienteResult = GetTokenExpedienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenBUIAuth", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetTokenBUIAuthRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid buId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public Recauda_PagosService.Contribuyente contribuyenteAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> idBUCS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> idMiBA;
        
        public GetTokenBUIAuthRequest()
        {
        }
        
        public GetTokenBUIAuthRequest(System.Guid buId, string user, string pass, Recauda_PagosService.Contribuyente contribuyenteAuth, System.Nullable<System.Guid> idBUCS, System.Nullable<System.Guid> idMiBA)
        {
            this.buId = buId;
            this.user = user;
            this.pass = pass;
            this.contribuyenteAuth = contribuyenteAuth;
            this.idBUCS = idBUCS;
            this.idMiBA = idMiBA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenBUIAuthResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetTokenBUIAuthResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Recauda_PagosService.RespuestaGetTokenBUI GetTokenBUIAuthResult;
        
        public GetTokenBUIAuthResponse()
        {
        }
        
        public GetTokenBUIAuthResponse(Recauda_PagosService.RespuestaGetTokenBUI GetTokenBUIAuthResult)
        {
            this.GetTokenBUIAuthResult = GetTokenBUIAuthResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenDueDate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetTokenDueDateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Recauda_PagosService.Contribuyente contribuyente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Recauda_PagosService.Concepto[] conceptos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime dueDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string observacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string idTramiteDependencia;
        
        public GetTokenDueDateRequest()
        {
        }
        
        public GetTokenDueDateRequest(Recauda_PagosService.Contribuyente contribuyente, Recauda_PagosService.Concepto[] conceptos, System.DateTime dueDate, string observacion, string user, string pass, string idTramiteDependencia)
        {
            this.contribuyente = contribuyente;
            this.conceptos = conceptos;
            this.dueDate = dueDate;
            this.observacion = observacion;
            this.user = user;
            this.pass = pass;
            this.idTramiteDependencia = idTramiteDependencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenDueDateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetTokenDueDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> GetTokenDueDateResult;
        
        public GetTokenDueDateResponse()
        {
        }
        
        public GetTokenDueDateResponse(System.Nullable<System.Guid> GetTokenDueDateResult)
        {
            this.GetTokenDueDateResult = GetTokenDueDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetToken", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Recauda_PagosService.Contribuyente contribuyente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Recauda_PagosService.Concepto[] conceptos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string observacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string idTramiteDependencia;
        
        public GetTokenRequest()
        {
        }
        
        public GetTokenRequest(Recauda_PagosService.Contribuyente contribuyente, Recauda_PagosService.Concepto[] conceptos, string observacion, string user, string pass, string idTramiteDependencia)
        {
            this.contribuyente = contribuyente;
            this.conceptos = conceptos;
            this.observacion = observacion;
            this.user = user;
            this.pass = pass;
            this.idTramiteDependencia = idTramiteDependencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> GetTokenResult;
        
        public GetTokenResponse()
        {
        }
        
        public GetTokenResponse(System.Nullable<System.Guid> GetTokenResult)
        {
            this.GetTokenResult = GetTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenPagoVoluntario", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetTokenPagoVoluntarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Recauda_PagosService.Contribuyente contribuyente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string codigoBarra;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string observacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string pass;
        
        public GetTokenPagoVoluntarioRequest()
        {
        }
        
        public GetTokenPagoVoluntarioRequest(Recauda_PagosService.Contribuyente contribuyente, string codigoBarra, string observacion, string user, string pass)
        {
            this.contribuyente = contribuyente;
            this.codigoBarra = codigoBarra;
            this.observacion = observacion;
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenPagoVoluntarioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetTokenPagoVoluntarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> GetTokenPagoVoluntarioResult;
        
        public GetTokenPagoVoluntarioResponse()
        {
        }
        
        public GetTokenPagoVoluntarioResponse(System.Nullable<System.Guid> GetTokenPagoVoluntarioResult)
        {
            this.GetTokenPagoVoluntarioResult = GetTokenPagoVoluntarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    internal interface PagosServiceSoapChannel : Recauda_PagosService.PagosServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    internal partial class PagosServiceSoapClient : System.ServiceModel.ClientBase<Recauda_PagosService.PagosServiceSoap>, Recauda_PagosService.PagosServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PagosServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PagosServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), PagosServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagosServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PagosServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagosServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PagosServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagosServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Recauda_PagosService.Concepto[]> GetConceptosAsync(string user, string pass)
        {
            return base.Channel.GetConceptosAsync(user, pass);
        }
        
        public System.Threading.Tasks.Task<Recauda_PagosService.Concepto[]> GetConceptosVigentesAsync(string user, string pass)
        {
            return base.Channel.GetConceptosVigentesAsync(user, pass);
        }
        
        public System.Threading.Tasks.Task<Recauda_PagosService.Concepto[]> GetImporteAsync(Recauda_PagosService.Concepto[] conceptos, string user, string pass)
        {
            return base.Channel.GetImporteAsync(conceptos, user, pass);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Recauda_PagosService.GetTokenExpedienteResponse> Recauda_PagosService.PagosServiceSoap.GetTokenExpedienteAsync(Recauda_PagosService.GetTokenExpedienteRequest request)
        {
            return base.Channel.GetTokenExpedienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Recauda_PagosService.GetTokenExpedienteResponse> GetTokenExpedienteAsync(Recauda_PagosService.Contribuyente contribuyente, Recauda_PagosService.Concepto[] conceptos, string nroExpediente, string observacion, string user, string pass)
        {
            Recauda_PagosService.GetTokenExpedienteRequest inValue = new Recauda_PagosService.GetTokenExpedienteRequest();
            inValue.contribuyente = contribuyente;
            inValue.conceptos = conceptos;
            inValue.nroExpediente = nroExpediente;
            inValue.observacion = observacion;
            inValue.user = user;
            inValue.pass = pass;
            return ((Recauda_PagosService.PagosServiceSoap)(this)).GetTokenExpedienteAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<Recauda_PagosService.RespuestaGetTokenBUI> GetTokenBUIPEAsync(System.Guid buId, string user, string pass, System.Guid idMiBA)
        {
            return base.Channel.GetTokenBUIPEAsync(buId, user, pass, idMiBA);
        }
        
        public System.Threading.Tasks.Task<Recauda_PagosService.RespuestaGetTokenBUI> GetTokenBUIAsync(System.Guid buId, string user, string pass)
        {
            return base.Channel.GetTokenBUIAsync(buId, user, pass);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Recauda_PagosService.GetTokenBUIAuthResponse> Recauda_PagosService.PagosServiceSoap.GetTokenBUIAuthAsync(Recauda_PagosService.GetTokenBUIAuthRequest request)
        {
            return base.Channel.GetTokenBUIAuthAsync(request);
        }
        
        public System.Threading.Tasks.Task<Recauda_PagosService.GetTokenBUIAuthResponse> GetTokenBUIAuthAsync(System.Guid buId, string user, string pass, Recauda_PagosService.Contribuyente contribuyenteAuth, System.Nullable<System.Guid> idBUCS, System.Nullable<System.Guid> idMiBA)
        {
            Recauda_PagosService.GetTokenBUIAuthRequest inValue = new Recauda_PagosService.GetTokenBUIAuthRequest();
            inValue.buId = buId;
            inValue.user = user;
            inValue.pass = pass;
            inValue.contribuyenteAuth = contribuyenteAuth;
            inValue.idBUCS = idBUCS;
            inValue.idMiBA = idMiBA;
            return ((Recauda_PagosService.PagosServiceSoap)(this)).GetTokenBUIAuthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Recauda_PagosService.GetTokenDueDateResponse> Recauda_PagosService.PagosServiceSoap.GetTokenDueDateAsync(Recauda_PagosService.GetTokenDueDateRequest request)
        {
            return base.Channel.GetTokenDueDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Recauda_PagosService.GetTokenDueDateResponse> GetTokenDueDateAsync(Recauda_PagosService.Contribuyente contribuyente, Recauda_PagosService.Concepto[] conceptos, System.DateTime dueDate, string observacion, string user, string pass, string idTramiteDependencia)
        {
            Recauda_PagosService.GetTokenDueDateRequest inValue = new Recauda_PagosService.GetTokenDueDateRequest();
            inValue.contribuyente = contribuyente;
            inValue.conceptos = conceptos;
            inValue.dueDate = dueDate;
            inValue.observacion = observacion;
            inValue.user = user;
            inValue.pass = pass;
            inValue.idTramiteDependencia = idTramiteDependencia;
            return ((Recauda_PagosService.PagosServiceSoap)(this)).GetTokenDueDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Recauda_PagosService.GetTokenResponse> Recauda_PagosService.PagosServiceSoap.GetTokenAsync(Recauda_PagosService.GetTokenRequest request)
        {
            return base.Channel.GetTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<Recauda_PagosService.GetTokenResponse> GetTokenAsync(Recauda_PagosService.Contribuyente contribuyente, Recauda_PagosService.Concepto[] conceptos, string observacion, string user, string pass, string idTramiteDependencia)
        {
            Recauda_PagosService.GetTokenRequest inValue = new Recauda_PagosService.GetTokenRequest();
            inValue.contribuyente = contribuyente;
            inValue.conceptos = conceptos;
            inValue.observacion = observacion;
            inValue.user = user;
            inValue.pass = pass;
            inValue.idTramiteDependencia = idTramiteDependencia;
            return ((Recauda_PagosService.PagosServiceSoap)(this)).GetTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Recauda_PagosService.GetTokenPagoVoluntarioResponse> Recauda_PagosService.PagosServiceSoap.GetTokenPagoVoluntarioAsync(Recauda_PagosService.GetTokenPagoVoluntarioRequest request)
        {
            return base.Channel.GetTokenPagoVoluntarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Recauda_PagosService.GetTokenPagoVoluntarioResponse> GetTokenPagoVoluntarioAsync(Recauda_PagosService.Contribuyente contribuyente, string codigoBarra, string observacion, string user, string pass)
        {
            Recauda_PagosService.GetTokenPagoVoluntarioRequest inValue = new Recauda_PagosService.GetTokenPagoVoluntarioRequest();
            inValue.contribuyente = contribuyente;
            inValue.codigoBarra = codigoBarra;
            inValue.observacion = observacion;
            inValue.user = user;
            inValue.pass = pass;
            return ((Recauda_PagosService.PagosServiceSoap)(this)).GetTokenPagoVoluntarioAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<Recauda_PagosService.EstadoPago> GetEstadoPagoAsync(System.Guid token, string user, string pass)
        {
            return base.Channel.GetEstadoPagoAsync(token, user, pass);
        }
        
        public System.Threading.Tasks.Task<Recauda_PagosService.EstadoPagoV2> GetEstadoPagoV2Async(System.Guid token, string user, string pass)
        {
            return base.Channel.GetEstadoPagoV2Async(token, user, pass);
        }
        
        public System.Threading.Tasks.Task<Recauda_PagosService.EstadoPagoV2[]> GetEstadoPagosAsync(System.DateTime desde, System.DateTime hasta, string tipoDoc, string nroDoc, string user, string pass)
        {
            return base.Channel.GetEstadoPagosAsync(desde, hasta, tipoDoc, nroDoc, user, pass);
        }
        
        public System.Threading.Tasks.Task<Recauda_PagosService.EstadoPago> GetEstadoPagoSuaciAsync(string nroSuaci, string user, string pass)
        {
            return base.Channel.GetEstadoPagoSuaciAsync(nroSuaci, user, pass);
        }
        
        public System.Threading.Tasks.Task<string> GetTimbradoDigitalAsync(System.Guid token, string user, string pass)
        {
            return base.Channel.GetTimbradoDigitalAsync(token, user, pass);
        }
        
        public System.Threading.Tasks.Task<string> GetMedioPagoPorIdCobroAsync(System.Guid idCobro)
        {
            return base.Channel.GetMedioPagoPorIdCobroAsync(idCobro);
        }
        
        public System.Threading.Tasks.Task<string> GetCodigoAutorizacionAsync(System.Guid idCobro)
        {
            return base.Channel.GetCodigoAutorizacionAsync(idCobro);
        }
        
        public System.Threading.Tasks.Task<string> ProcesarBajaFacturaPMCAsync(string token, string nroBoleta)
        {
            return base.Channel.ProcesarBajaFacturaPMCAsync(token, nroBoleta);
        }
        
        public System.Threading.Tasks.Task<Recauda_PagosService.PDFResponse> EnviarCbteDePagoPorEmailAsync(System.Guid token, System.Guid userId)
        {
            return base.Channel.EnviarCbteDePagoPorEmailAsync(token, userId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PagosServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PagosServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PagosServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:59337/PagosService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PagosServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:59337/PagosService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PagosServiceSoap,
            
            PagosServiceSoap12,
        }
    }
}
